name: Java CI-CD with Gradle and Azure

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew shadowJar
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-jars
        path: |
          build/libs
    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh/
        echo "$SSH_KEY" > ~/.ssh/azure.key
        chmod 600 ~/.ssh/azure.key
        cat >>~/.ssh/config <<END
        Host azure
          HostName $SSH_HOST
          User $SSH_USER
          IdentityFile ~/.ssh/azure.key
          StrictHostKeyChecking no
        END
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
    - name: Stop the bot
      run: ssh azure "sudo pkill -f 'java -jar'"
    - name: Add credentials
      run: |
        ssh azure 'echo "${{ secrets.CREDENTIALS }}" > /RemiBot/serviceAccountKey.json'
        ssh azure 'sudo chmod 700 /RemiBot/serviceAccountKey.json'
    - name: Upload jar on Azure VM
      run: |
        ssh azure 'echo "export OPENAI_TOKEN=${{ secrets.OPENAI_TOKEN }}; /usr/lib/jvm/java-16-openjdk-amd64/bin/java -jar /RemiBot/RemiBot-1.0-all.jar \"${{ secrets.BOT_TOKEN }}\" \"${{ secrets.CSV_VOCABULAIRE_JP }}\" \"${{ secrets.MDP_FB }}\" \"${{ secrets.AUTHORIZATION_REMINATOR392 }}\" \"${{ secrets.AUTHORIZATION_MOUMOUNI }}\" \"${{ secrets.AUTHORIZATION_DREAM_PLUME }}\" \"${{ secrets.AUTHORIZATION_DORIAN }}\" >> /RemiBot/log.txt 2>> /RemiBot/log.txt" > /RemiBot/run.sh'
        ssh azure 'sudo chmod 700 /RemiBot/run.sh'
        scp build/libs/RemiBot-1.0-all.jar azure:/RemiBot
    - name: Start the bot
      run: ssh azure 'cd /RemiBot ; sudo ./run.sh > /dev/null' &
